name: Production - Deploy dnd-timeline examples
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy_production: 
    uses: ./.github/workflows/deploy-examples.yml
    with:
      environment: Preview
    secrets: inherit
