name: Preview - Deploy Examples
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy_preview: 
    uses: ./.github/workflows/deploy-examples.yml
    with:
      environment: Preview
    secrets: inherit
