name: Deploy dnd-timeline examples template
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Log secrets
        run: |
          echo $VERCEL_PROJECT_ID
          echo $VERCEL_TOKEN
          echo $VERCEL_ORG_ID
      - name: Deploy to Vercel
        run: vercel --prod --yes
