name: Production - Deploy Examples
on:
  push:
    branches:
      - main

jobs:
  deploy_production: 
    uses: ./.github/workflows/deploy-examples.yml
    with:
      environment: Production
      isProd: true
    secrets: inherit
