name: Deploy dnd-timeline examples
on:
  push:
    branches:
    - main

jobs:
  deploy_timeaxis: 
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Production - dnd-timeline-timeaxis
    secrets: inherit

